---
abstract: 'a coderef for use in Moose triggers that will lock hashrefs and arrayrefs'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::Fatal: 0
  Test::More: 0.96
  Test::Requires: 0
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.013, CPAN::Meta::Converter version 2.120921'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sub-Trigger-Lock
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  Sub::Trigger::Lock:
    file: lib/Sub/Trigger/Lock.pm
    version: 0.001
requires:
  Exporter::Tiny: 0
  Scope::Guard: 0
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/Sub-Trigger-Lock/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Sub-Trigger-Lock
  homepage: https://metacpan.org/release/Sub-Trigger-Lock
  license: http://dev.perl.org/licenses/
version: 0.001
